import { useEffect, useState } from "react";

const ASSET = "/source-assets";
const posts = [
  { date: "December 23, 2025", title: "December 11: Planning and Zoning Work Session Recap", excerpt: "A short summary of the Holly Springs planning and zoning work session, including the latest discussion around zoning declarations.", slug: "planning-and-zoning-work-session-recap", image: `${ASSET}/development-plan.jpg` },
  { date: "December 2, 2025", title: "An update", excerpt: "The latest news from the campaign and what neighbors can do next.", slug: "an-update", image: `${ASSET}/proposed-layout.png` },
  { date: "November 8, 2025", title: "Come and join us!", excerpt: "Join us at the Falls of Cherokee HOA meeting to hear the latest on the Brock Built Homes proposals.", slug: "come-and-join-us", image: `${ASSET}/sixes-mill.jpg` },
  { date: "November 1, 2025", title: "Why we started", excerpt: "We live in Falls of Cherokee and founded Save Sixes Rd to protect our community's quality of life.", slug: "why-we-started", image: `${ASSET}/nature-sixes.jpg` },
];
const libraryItems = [
  { title: "Brock Built does not care about county citizens", href: "https://drive.google.com/file/d/1_VBuIEAw-s0lF2jghrXnGQVa5LCPXO4R/view?usp=sharing", type: "Analysis" },
  { title: "Sixes Road Traffic Impact Assessment", href: "https://drive.google.com/file/d/13a6ALffKkkiFJB9QJn9_iXrkfU7sWdiG/view?usp=sharing", type: "Traffic" },
  { title: "Variances are not due to hardships", href: "https://drive.google.com/file/d/16MRCn_K3LMk2kyEzwKCEf-6bduBSojpu/view?usp=drive_link", type: "Analysis" },
  { title: "Annexation Application - A-04-2025", href: "https://drive.google.com/file/d/1a0x_yDqGNSM5-YsJZe8VGVhB_kDEGZJt/view?usp=drive_link", type: "Application" },
  { title: "Rezoning Application - MA-09-2025", href: "https://drive.google.com/file/d/1cJlrkxoV6prEeTA1XCb8b3L6jJ4Bssm0/view?usp=sharing", type: "Application" },
  { title: "Variances Application - V-04-2025", href: "https://drive.google.com/file/d/1g5x3CIZ97cpoHGlrtVXB0OjyikMSMfJn/view?usp=drive_link", type: "Application" },
];

function navigate(path) { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); window.scrollTo({ top: 0, behavior: "smooth" }); }
function NavLink({ href, children, onClick }) { return <a href={href} onClick={(event) => { event.preventDefault(); onClick?.(); navigate(href); }}>{children}</a>; }

function SiteHeader() {
  const [open, setOpen] = useState(false);
  const links = [["/about", "About"], ["/library", "The evidence"], ["/blog", "Blog"], ["/petiton", "Take action"]];
  return <header className="site-header"><div className="header-inner"><NavLink href="/" onClick={() => setOpen(false)}><img className="brand-mark" src={`${ASSET}/logo-primary.png`} alt="Save Sixes Rd Green Not Gridlock" /></NavLink><nav className={`main-nav ${open ? "is-open" : ""}`} aria-label="Primary navigation">{links.map(([href, label]) => <NavLink key={href} href={href} onClick={() => setOpen(false)}>{label}</NavLink>)}<a className="header-action" href="/petiton" onClick={(event) => { event.preventDefault(); setOpen(false); navigate("/petiton"); }}>Sign the petition</a></nav><button className="menu-toggle" type="button" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? "Close" : "Menu"}</button></div></header>;
}

function NewsletterForm({ compact = false }) {
  const [email, setEmail] = useState(""); const [submitted, setSubmitted] = useState(false);
  if (submitted) return <div className={`form-success ${compact ? "compact" : ""}`} role="status"><strong>Check your inbox.</strong><span>We sent a confirmation link to {email}.</span></div>;
  return <form className={`newsletter-form ${compact ? "compact" : ""}`} onSubmit={(event) => { event.preventDefault(); if (email.trim()) setSubmitted(true); }}><label className="sr-only" htmlFor={compact ? "compact-email" : "email"}>Email address</label><input id={compact ? "compact-email" : "email"} type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email address" /><button type="submit">Sign up</button>{!compact && <small>We respect your privacy. Unsubscribe anytime.</small>}</form>;
}

function Footer() { return <footer className="site-footer"><div className="footer-grid"><div className="footer-brand"><img src={`${ASSET}/logo-primary.png`} alt="Save Sixes Rd" /><p>A resident-led campaign for responsible growth, safer roads, and a stronger future.</p></div><div><p className="footer-label">Explore</p><NavLink href="/about">About</NavLink><NavLink href="/library">The evidence</NavLink><NavLink href="/blog">Blog</NavLink></div><div><p className="footer-label">Get involved</p><NavLink href="/petiton">Sign the petition</NavLink><a href="mailto:info@savesixesrd.org">Contact us</a><a href="https://www.instagram.com/savesixesrd/" target="_blank" rel="noreferrer">Instagram</a></div><div className="footer-contact"><p className="footer-label">Stay informed</p><p>Join neighbors across the Sixes Road corridor.</p><NewsletterForm compact /></div></div><div className="footer-bottom"><span>© 2026 Save Sixes Road</span><span>info@savesixesrd.org</span></div></footer>; }
function PageIntro({ eyebrow, title, copy }) { return <section className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy && <p className="intro-copy">{copy}</p>}</section>; }

function HomePage() {
  return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Protect Sixes Road</p><h1>Save Sixes Road.<br />Protect our lakes,<br />our roads, and<br />our way of life.</h1><p className="hero-subtitle">A resident-led campaign to prevent high-density overdevelopment along the Sixes Road corridor.</p><div className="hero-actions"><a className="button button-primary" href="/petiton" onClick={(event) => { event.preventDefault(); navigate("/petiton"); }}>Sign the petition</a><a className="text-link" href="#the-threat">Learn why it matters <span>→</span></a></div></div><div className="hero-image"><img src={`${ASSET}/lake-allatoona.jpg`} alt="Lake Allatoona and the green landscape around Sixes Road" /></div></section><section className="value-strip" aria-label="Campaign priorities"><div><span className="value-number">01</span><h2>Protect what we love</h2><p>Keep our forests, lakes, and neighborhood character for generations to come.</p></div><div><span className="value-number">02</span><h2>Prevent gridlock</h2><p>High-density development means more traffic on roads that cannot take it.</p></div><div><span className="value-number">03</span><h2>Our community, our voice</h2><p>Neighbors working together for responsible growth and a stronger future.</p></div></section><section className="threat-section" id="the-threat"><div className="threat-copy"><p className="eyebrow light">The threat</p><h2>A plan that doesn't fit our community</h2><p>A proposed high-density townhome development on Sixes Road would bring hundreds of new units to an area with narrow roads, limited infrastructure, and sensitive natural resources.</p><a className="button button-light" href="/library" onClick={(event) => { event.preventDefault(); navigate("/library"); }}>See the proposed plan</a></div><div className="threat-image"><img src={`${ASSET}/proposed-layout.png`} alt="Proposed development layout on Sixes Road" /></div></section><section className="updates-section section-wrap"><div className="section-heading"><div><p className="eyebrow">Latest updates</p><h2>Stay close to the work.</h2></div><NavLink href="/blog">Read the blog <span>→</span></NavLink></div><div className="updates-grid"><div className="post-list">{posts.slice(0, 3).map((post) => <PostRow key={post.slug} post={post} />)}</div><div className="library-invite"><p className="eyebrow">Our library</p><h3>See the facts.<br />Share the truth.</h3><p>Explore maps, documents, traffic data, and resources about the proposed development and its impact.</p><NavLink href="/library">Browse the library <span>→</span></NavLink></div></div></section><NewsletterBand /></main>;
}
function PostRow({ post }) { return <article className="post-row"><img src={post.image} alt="" /><div><p className="post-date">{post.date}</p><h3>{post.title}</h3><p>{post.excerpt}</p><a href={`/blog/${post.slug}`} onClick={(event) => { event.preventDefault(); navigate(`/blog/${post.slug}`); }}>Read update <span>→</span></a></div></article>; }
function NewsletterBand() { return <section className="newsletter-band"><div><p className="eyebrow">Join the neighborhood conversation</p><h2>Stay informed.<br />Get involved.</h2></div><div><p>Sign up for email updates on meetings, actions, and ways to make your voice heard.</p><NewsletterForm /></div></section>; }

function BlogPage() { return <main><PageIntro eyebrow="Campaign blog" title="The work is ongoing." copy="Follow the latest meetings, proposals, and actions from neighbors across the Sixes Road corridor." /><section className="blog-grid section-wrap">{posts.map((post) => <article className="blog-card" key={post.slug}><img src={post.image} alt="" /><div className="blog-card-content"><p className="post-date">{post.date}</p><h2>{post.title}</h2><p>{post.excerpt}</p><a href={`/blog/${post.slug}`} onClick={(event) => { event.preventDefault(); navigate(`/blog/${post.slug}`); }}>Read more <span>→</span></a></div></article>)}</section><NewsletterBand /></main>; }
function ArticlePage({ post }) { return <main><PageIntro eyebrow={post.date} title={post.title} copy={post.excerpt} /><article className="article-page section-wrap"><img src={post.image} alt="" /><div className="article-copy"><p>Save Sixes Rd is keeping neighbors informed as the proposal moves through the planning process. We are collecting public documents, sharing the record, and asking for decisions that respect the roads, schools, waterways, and people who already call this corridor home.</p><p>Read the supporting documents in the <NavLink href="/library">evidence library</NavLink>, then sign the petition or subscribe for the next update.</p><a className="button button-primary" href="/petiton" onClick={(event) => { event.preventDefault(); navigate("/petiton"); }}>Take action</a></div></article><NewsletterBand /></main>; }
function LibraryPage() { return <main><PageIntro eyebrow="The evidence" title="See the facts. Share the truth." copy="The public record matters. Find the applications, plans, analysis, and traffic information collected by the Save Sixes community." /><section className="evidence-feature"><div className="evidence-image"><img src={`${ASSET}/development-plan.jpg`} alt="Preliminary site plan for the proposed Sixes Road residential development" /></div><div className="evidence-copy"><p className="eyebrow">Featured document</p><h2>A closer look at the proposed plan.</h2><p>The current proposal would place a high number of new homes along a corridor that already carries daily traffic, schools, and neighborhood access.</p><a className="button button-primary" href={libraryItems[0].href} target="_blank" rel="noreferrer">Open the analysis</a></div></section><section className="library-section section-wrap"><div className="section-heading"><div><p className="eyebrow">Document library</p><h2>Applications, analysis, and comments.</h2></div><p>Public materials collected for the community.</p></div><div className="library-list">{libraryItems.map((item) => <a className="library-row" key={item.title} href={item.href} target="_blank" rel="noreferrer"><span className="library-type">{item.type}</span><strong>{item.title}</strong><span className="library-arrow">↗</span></a>)}</div></section></main>; }
function AboutPage() { return <main><PageIntro eyebrow="Who we are" title="A community-led campaign for responsible growth." copy="Save Sixes Rd is made up of residents, neighbors, and concerned citizens who believe development should respect the area's infrastructure, environment, and quality of life." /><section className="about-grid section-wrap"><div className="about-image"><img src={`${ASSET}/sixes-mill.jpg`} alt="A green local landscape near Sixes Road" /></div><div className="about-copy"><p>We cherish the open spaces, trees, waterways, and wildlife that make this corridor home. Morning commutes are already slow, and traffic near the Kroger area often gridlocks.</p><p>Our goal is not to stop growth. It is to ensure that growth is sustainable, well-planned, and aligned with the community's long-term vision.</p><p>We advocate for smarter zoning decisions, increased transparency from local officials, and meaningful community engagement in shaping our future.</p><a className="button button-primary" href="/petiton" onClick={(event) => { event.preventDefault(); navigate("/petiton"); }}>Get involved</a></div></section><NewsletterBand /></main>; }
function PetitionPage() { return <main><PageIntro eyebrow="Take action" title="Add your voice to the record." copy="Please complete the petition to join the effort to protect the character, safety, and livability of the Sixes Road corridor." /><section className="petition-grid section-wrap"><div className="petition-card"><p className="eyebrow">The proposal</p><h2>20 acres.<br />184 units.<br />High density.</h2><p>Brock Built Homes presented this concept for a new development along Sixes Road. The community is asking for responsible, transparent planning.</p><a className="button button-primary" href="https://www.savesixesrd.org/petiton" target="_blank" rel="noreferrer">Open the petition</a><small>The petition currently opens on the existing petition service while the new site is being completed.</small></div><div className="petition-image"><img src={`${ASSET}/proposed-layout.png`} alt="Proposed development plan" /></div></section><NewsletterBand /></main>; }

function App() { const [path, setPath] = useState(window.location.pathname); useEffect(() => { const handler = () => setPath(window.location.pathname); window.addEventListener("popstate", handler); return () => window.removeEventListener("popstate", handler); }, []); let page = <HomePage />; if (path === "/blog") page = <BlogPage />; if (path.startsWith("/blog/")) page = <ArticlePage post={posts.find((item) => path.endsWith(item.slug)) || posts[0]} />; if (path === "/library") page = <LibraryPage />; if (path === "/about") page = <AboutPage />; if (path === "/petiton" || path === "/petition") page = <PetitionPage />; return <><SiteHeader />{page}<Footer /></>; }
export { App };
